export const CA = {
      "atj": "CA",
      "chp": "CA",
      "cr": "CA",
      "crj": "CA",
      "crk": "CA",
      "crl": "CA",
      "crm": "CA",
      "csw": "CA",
      "den": "CA",
      "dgr": "CA",
      "gwi": "CA",
      "ikt": "CA",
      "iu": "CA",
      "moe": "CA",
      "moh": "CA",
      "nsk": "CA",
      "pdt": "CA",
      "scs": "CA"
    };
