export const CM = {
      "agq": "CM",
      "bas": "CM",
      "bax": "CM",
      "bbj": "CM",
      "bfd": "CM",
      "bkm": "CM",
      "bss": "CM",
      "bum": "CM",
      "byv": "CM",
      "dua": "CM",
      "ewo": "CM",
      "fub": "CM",
      "jgo": "CM",
      "ken": "CM",
      "kkj": "CM",
      "ksf": "CM",
      "maf": "CM",
      "mgo": "CM",
      "mua": "CM",
      "nmg": "CM",
      "nnh": "CM",
      "yav": "CM",
      "ybb": "CM"
    };
