export const CN = {
      "bo": "CN",
      "gan": "CN",
      "hak": "CN",
      "hmd": "CN",
      "hsn": "CN",
      "ii": "CN",
      "khb": "CN",
      "kk-Arab": "CN",
      "ky-Arab": "CN",
      "lcp": "CN",
      "lis": "CN",
      "lzh": "CN",
      "mn-Mong": "CN",
      "nan": "CN",
      "nxq": "CN",
      "pal-Phlp": "CN",
      "tdd": "CN",
      "txg": "CN",
      "ug": "CN",
      "wuu": "CN",
      "xmn": "CN",
      "yue-Hans": "CN",
      "za": "CN",
      "zh": "CN"
    };
