export const PH = {
      "bhk": "PH",
      "bik": "PH",
      "bku": "PH",
      "bto": "PH",
      "ceb": "PH",
      "cps": "PH",
      "fil": "PH",
      "hil": "PH",
      "hnn": "PH",
      "ilo": "PH",
      "krj": "PH",
      "mdh": "PH",
      "pag": "PH",
      "pam": "PH",
      "tbw": "PH",
      "tl": "PH",
      "tsg": "PH",
      "war": "PH"
    };
