export const PK = {
      "bal": "PK",
      "bft": "PK",
      "bgn": "PK",
      "brh": "PK",
      "btv": "PK",
      "gjk": "PK",
      "gju": "PK",
      "hnd": "PK",
      "hno": "PK",
      "khw": "PK",
      "kvx": "PK",
      "kxp": "PK",
      "lah": "PK",
      "mvy": "PK",
      "'pa-Arab'": "PK",
      "pra": "PK",
      "sd": "PK",
      "skr": "PK",
      "'tg-Arab'": "PK",
      "ur": "PK"
    };
